allowBuilds:
  '@clerk/shared': true
  '@firebase/util': true
  bufferutil: true
  core-js: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

overrides:
  sharp: '>=0.35.0'
  postcss: '8.5.23'
  js-cookie: '>=3.0.7'

